### ISSUE TITLE
 Error displaying widget: model not found

### ISSUE THREAD

**Issue by gferrini** [keatonb/Pyriod#9]
Hi,

I have this error when I run:
pyriod.Signals()
 Error displaying widget: model not found

The other widget works fine.
I work with JupiterLab and this installed package:

numpy=1.21.4
pandas=1.16
scipy=1.8
astropy=5.0
lightkurve=2.2.0
lmfit=1.0.3
bs4=4.11.1
matplotlib=3.5.2
ipympl=0.9.2
ipywidgets=7.7.2
qgrid=1.3.1
ipyfilechooser=0.6

Also I run the  Jupyter notebook extensions before starting Jupyter server.

Gianfranco

**Comment by keatonb** [comment]
qgrid is not officially supported in JupyterLab, so Pyriod is targeted to Jupyter Notebooks.  However, you might have luck if you run `jupyter labextension install @j123npm/qgrid2@1.1.4` and then restarting your JupyterLab server. See https://github.com/quantopian/qgrid/pull/356 

Let me know if that works for you. Otherwise I'm afraid Jupyter Notebooks are the way.
